
[merge]
command = "bash"
args = [
    "-c",
    "cp {{ .Target }} {{ .Target }}.base && code --new-window --wait --merge {{ .Destination }} {{ .Target }} {{ .Target }}.base {{ .Source }}",
]

[git]
    autoCommit = true
    autoPush = true

[template]
    options = ["missingkey=zero"]

[diff]
    exclude = ["run_aim-setup.sh"]

